apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baseline-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hardikpatel29/argocd-install.git
    path: charts/baseline/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true